### ISSUE TITLE
Getting error in deploy_token 

### ISSUE THREAD

**Issue by arre-ankit** [sendaifun/solana-agent-kit#33]
Issue:

![image](https://github.com/user-attachments/assets/ac9ceb5a-caf1-4ba6-98d4-8be48d564430)
![image](https://github.com/user-attachments/assets/cf496bc3-401b-471b-8aab-4e4e5bb3853a)

**Comment by arre-ankit** [comment]
Getting this error when deploy_token
RPC: https://api.devnet.solana.com


D:\Solana_AI_Hackathone\solana-ai-agent-example\dist\solana-agent-kit\src\tools\deploy_token.js:51
        throw new Error(`Token deployment failed: ${error.message}`);
              ^

Error: Token deployment failed: The provided program name [splAssociatedToken] is not recognized in the [devnet] cluster. Did you forget to register this program? If so, you may use "context.programs.add(myProgram)" to fix this.

Source: SDK

    at deploy_token (D:\Solana_AI_Hackathone\solana-ai-agent-example\dist\solana-agent-kit\src\tools\deploy_token.js:51:15)
    at deploy (D:\Solana_AI_Hackathone\solana-ai-agent-example\dist\src\index.js:14:58)
    at Object.<anonymous> (D:\Solana_AI_Hackathone\solana-ai-agent-example\dist\src\index.js:19:1)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)
    at Module.load (node:internal/modules/cjs/loader:1317:32)
    at Module._load (node:internal/modules/cjs/loader:1127:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:166:5)

Node.js v22.6.0


My code: 
```
import { SolanaAgentKit, createSolanaTools } from "solana-agent-kit";
import { deploy_token } from "../solana-agent-kit/src/tools/deploy_token"
import { deploy_collection } from "../solana-agent-kit/src/tools/deploy_collection"
import dotenv from "dotenv";
import { fetchPrice } from "../solana-agent-kit/src/tools/fetch_price";


dotenv.config();
// Initialize with private key and optional RPC URL
const agent = new SolanaAgentKit(
  process.env.SOLANA_PRIVATE_KEY as string,
  process.env.RPC_URL as string,
  process.env.OPENAI_API_KEY as string
);

async function deploy() {
    const result = await deploy_token(
    agent,
    "Ankit Token",
    "https://arweave.net/metadata.json",
    "ANK",
    9, // decimals
    1000000 // initial supply
    );
    console.log("Token Mint Address:", result.mint.toString());
}

deploy();

async function fetchPrices() {
const price = await fetchPrice(
    agent,
    "JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN" // Token mint address
  );
  console.log("Price in USDC:", price);
}

fetchPrices();
```

**Comment by arre-ankit** [comment]
Error in deploy_tokey
RPC: https://api.devnet.solana.com


D:\Solana_AI_Hackathone\solana-ai-agent-example\dist\solana-agent-kit\src\tools\deploy_token.js:51
        throw new Error(`Token deployment failed: ${error.message}`);
              ^

Error: Token deployment failed: The provided program name [splAssociatedToken] is not recognized in the [devnet] cluster. Did you forget to register this program? If so, you may use "context.programs.add(myProgram)" to fix this.

Source: SDK

    at deploy_token (D:\Solana_AI_Hackathone\solana-ai-agent-example\dist\solana-agent-kit\src\tools\deploy_token.js:51:15)
    at deploy (D:\Solana_AI_Hackathone\solana-ai-agent-example\dist\src\index.js:14:58)
    at Object.<anonymous> (D:\Solana_AI_Hackathone\solana-ai-agent-example\dist\src\index.js:19:1)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)
    at Module.load (node:internal/modules/cjs/loader:1317:32)
    at Module._load (node:internal/modules/cjs/loader:1127:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:166:5)

Node.js v22.6.0



My Code
```
import { SolanaAgentKit, createSolanaTools } from "solana-agent-kit";
import { deploy_token } from "../solana-agent-kit/src/tools/deploy_token"
import { deploy_collection } from "../solana-agent-kit/src/tools/deploy_collection"
import dotenv from "dotenv";
import { fetchPrice } from "../solana-agent-kit/src/tools/fetch_price";


dotenv.config();
// Initialize with private key and optional RPC URL
const agent = new SolanaAgentKit(
  process.env.SOLANA_PRIVATE_KEY as string,
  process.env.RPC_URL as string,
  process.env.OPENAI_API_KEY as string
);

async function deploy() {
    const result = await deploy_token(
    agent,
    "Ankit Token",
    "https://arweave.net/metadata.json",
    "ANK",
    9, // decimals
    1000000 // initial supply
    );
    console.log("Token Mint Address:", result.mint.toString());
}

deploy();

async function fetchPrices() {
const price = await fetchPrice(
    agent,
    "JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN" // Token mint address
  );
  console.log("Price in USDC:", price);
}

fetchPrices();
```

**Comment by HongThaiPham** [comment]
![image](https://github.com/user-attachments/assets/6a9d4e9a-d4a6-4145-bea0-f469ecebe7c3)
Associated Token Program not recognized in the devnet cluster

**Comment by arre-ankit** [comment]
@HongThaiPham I am also facing same issue are you able to resolve it

**Comment by thearyanag** [comment]
#34

**Comment by arre-ankit** [comment]
Thanks! @thearyanag 
It worked!
